/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GoogleCallbackRouteImport } from './routes/google-callback'
import { Route as GithubCallbackRouteImport } from './routes/github-callback'
import { Route as DashboardLayoutRouteImport } from './routes/_dashboardLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardLayoutSettingsRouteImport } from './routes/_dashboardLayout/settings'
import { Route as DashboardLayoutDashboardRouteImport } from './routes/_dashboardLayout/dashboard'
import { Route as DashboardLayoutChannelsRouteImport } from './routes/_dashboardLayout/channels'
import { Route as DashboardLayoutBroadcastRouteImport } from './routes/_dashboardLayout/broadcast'
import { Route as DashboardLayoutAppSettingsRouteImport } from './routes/_dashboardLayout/app-settings'
import { Route as DashboardLayoutActivityRouteImport } from './routes/_dashboardLayout/activity'
import { Route as DashboardLayoutUsersIndexRouteImport } from './routes/_dashboardLayout/users/index'
import { Route as DashboardLayoutResourcesIndexRouteImport } from './routes/_dashboardLayout/resources.index'
import { Route as DashboardLayoutInviteCodesIndexRouteImport } from './routes/_dashboardLayout/invite-codes/index'
import { Route as DashboardLayoutCoursesIndexRouteImport } from './routes/_dashboardLayout/courses/index'
import { Route as DashboardLayoutArticlesIndexRouteImport } from './routes/_dashboardLayout/articles.index'
import { Route as DashboardLayoutUsersIdRouteImport } from './routes/_dashboardLayout/users/$id'
import { Route as DashboardLayoutInviteCodesNewRouteImport } from './routes/_dashboardLayout/invite-codes/new'
import { Route as DashboardLayoutCoursesNewRouteImport } from './routes/_dashboardLayout/courses/new'
import { Route as DashboardLayoutArticlesNewRouteImport } from './routes/_dashboardLayout/articles.new'
import { Route as DashboardLayoutArticlesIdRouteImport } from './routes/_dashboardLayout/articles.$id'
import { Route as DashboardLayoutInviteCodesEditIdRouteImport } from './routes/_dashboardLayout/invite-codes/edit.$id'
import { Route as DashboardLayoutCoursesEditIdRouteImport } from './routes/_dashboardLayout/courses/edit.$id'
import { Route as DashboardLayoutArticlesEditIdRouteImport } from './routes/_dashboardLayout/articles.edit.$id'
import { Route as DashboardLayoutCoursesSectionsSectionIdEditRouteImport } from './routes/_dashboardLayout/courses/sections/$sectionId/edit'
import { Route as DashboardLayoutCoursesLessonsLessonIdEditRouteImport } from './routes/_dashboardLayout/courses/lessons/$lessonId/edit'

const GoogleCallbackRoute = GoogleCallbackRouteImport.update({
  id: '/google-callback',
  path: '/google-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubCallbackRoute = GithubCallbackRouteImport.update({
  id: '/github-callback',
  path: '/github-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/_dashboardLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutSettingsRoute = DashboardLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutDashboardRoute =
  DashboardLayoutDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutChannelsRoute = DashboardLayoutChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutBroadcastRoute =
  DashboardLayoutBroadcastRouteImport.update({
    id: '/broadcast',
    path: '/broadcast',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutAppSettingsRoute =
  DashboardLayoutAppSettingsRouteImport.update({
    id: '/app-settings',
    path: '/app-settings',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutActivityRoute = DashboardLayoutActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutUsersIndexRoute =
  DashboardLayoutUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutResourcesIndexRoute =
  DashboardLayoutResourcesIndexRouteImport.update({
    id: '/resources/',
    path: '/resources/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutInviteCodesIndexRoute =
  DashboardLayoutInviteCodesIndexRouteImport.update({
    id: '/invite-codes/',
    path: '/invite-codes/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutCoursesIndexRoute =
  DashboardLayoutCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutArticlesIndexRoute =
  DashboardLayoutArticlesIndexRouteImport.update({
    id: '/articles/',
    path: '/articles/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutUsersIdRoute = DashboardLayoutUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutInviteCodesNewRoute =
  DashboardLayoutInviteCodesNewRouteImport.update({
    id: '/invite-codes/new',
    path: '/invite-codes/new',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutCoursesNewRoute =
  DashboardLayoutCoursesNewRouteImport.update({
    id: '/courses/new',
    path: '/courses/new',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutArticlesNewRoute =
  DashboardLayoutArticlesNewRouteImport.update({
    id: '/articles/new',
    path: '/articles/new',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutArticlesIdRoute =
  DashboardLayoutArticlesIdRouteImport.update({
    id: '/articles/$id',
    path: '/articles/$id',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutInviteCodesEditIdRoute =
  DashboardLayoutInviteCodesEditIdRouteImport.update({
    id: '/invite-codes/edit/$id',
    path: '/invite-codes/edit/$id',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutCoursesEditIdRoute =
  DashboardLayoutCoursesEditIdRouteImport.update({
    id: '/courses/edit/$id',
    path: '/courses/edit/$id',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutArticlesEditIdRoute =
  DashboardLayoutArticlesEditIdRouteImport.update({
    id: '/articles/edit/$id',
    path: '/articles/edit/$id',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutCoursesSectionsSectionIdEditRoute =
  DashboardLayoutCoursesSectionsSectionIdEditRouteImport.update({
    id: '/courses/sections/$sectionId/edit',
    path: '/courses/sections/$sectionId/edit',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutCoursesLessonsLessonIdEditRoute =
  DashboardLayoutCoursesLessonsLessonIdEditRouteImport.update({
    id: '/courses/lessons/$lessonId/edit',
    path: '/courses/lessons/$lessonId/edit',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/github-callback': typeof GithubCallbackRoute
  '/google-callback': typeof GoogleCallbackRoute
  '/activity': typeof DashboardLayoutActivityRoute
  '/app-settings': typeof DashboardLayoutAppSettingsRoute
  '/broadcast': typeof DashboardLayoutBroadcastRoute
  '/channels': typeof DashboardLayoutChannelsRoute
  '/dashboard': typeof DashboardLayoutDashboardRoute
  '/settings': typeof DashboardLayoutSettingsRoute
  '/articles/$id': typeof DashboardLayoutArticlesIdRoute
  '/articles/new': typeof DashboardLayoutArticlesNewRoute
  '/courses/new': typeof DashboardLayoutCoursesNewRoute
  '/invite-codes/new': typeof DashboardLayoutInviteCodesNewRoute
  '/users/$id': typeof DashboardLayoutUsersIdRoute
  '/articles': typeof DashboardLayoutArticlesIndexRoute
  '/courses': typeof DashboardLayoutCoursesIndexRoute
  '/invite-codes': typeof DashboardLayoutInviteCodesIndexRoute
  '/resources': typeof DashboardLayoutResourcesIndexRoute
  '/users': typeof DashboardLayoutUsersIndexRoute
  '/articles/edit/$id': typeof DashboardLayoutArticlesEditIdRoute
  '/courses/edit/$id': typeof DashboardLayoutCoursesEditIdRoute
  '/invite-codes/edit/$id': typeof DashboardLayoutInviteCodesEditIdRoute
  '/courses/lessons/$lessonId/edit': typeof DashboardLayoutCoursesLessonsLessonIdEditRoute
  '/courses/sections/$sectionId/edit': typeof DashboardLayoutCoursesSectionsSectionIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/github-callback': typeof GithubCallbackRoute
  '/google-callback': typeof GoogleCallbackRoute
  '/activity': typeof DashboardLayoutActivityRoute
  '/app-settings': typeof DashboardLayoutAppSettingsRoute
  '/broadcast': typeof DashboardLayoutBroadcastRoute
  '/channels': typeof DashboardLayoutChannelsRoute
  '/dashboard': typeof DashboardLayoutDashboardRoute
  '/settings': typeof DashboardLayoutSettingsRoute
  '/articles/$id': typeof DashboardLayoutArticlesIdRoute
  '/articles/new': typeof DashboardLayoutArticlesNewRoute
  '/courses/new': typeof DashboardLayoutCoursesNewRoute
  '/invite-codes/new': typeof DashboardLayoutInviteCodesNewRoute
  '/users/$id': typeof DashboardLayoutUsersIdRoute
  '/articles': typeof DashboardLayoutArticlesIndexRoute
  '/courses': typeof DashboardLayoutCoursesIndexRoute
  '/invite-codes': typeof DashboardLayoutInviteCodesIndexRoute
  '/resources': typeof DashboardLayoutResourcesIndexRoute
  '/users': typeof DashboardLayoutUsersIndexRoute
  '/articles/edit/$id': typeof DashboardLayoutArticlesEditIdRoute
  '/courses/edit/$id': typeof DashboardLayoutCoursesEditIdRoute
  '/invite-codes/edit/$id': typeof DashboardLayoutInviteCodesEditIdRoute
  '/courses/lessons/$lessonId/edit': typeof DashboardLayoutCoursesLessonsLessonIdEditRoute
  '/courses/sections/$sectionId/edit': typeof DashboardLayoutCoursesSectionsSectionIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboardLayout': typeof DashboardLayoutRouteWithChildren
  '/github-callback': typeof GithubCallbackRoute
  '/google-callback': typeof GoogleCallbackRoute
  '/_dashboardLayout/activity': typeof DashboardLayoutActivityRoute
  '/_dashboardLayout/app-settings': typeof DashboardLayoutAppSettingsRoute
  '/_dashboardLayout/broadcast': typeof DashboardLayoutBroadcastRoute
  '/_dashboardLayout/channels': typeof DashboardLayoutChannelsRoute
  '/_dashboardLayout/dashboard': typeof DashboardLayoutDashboardRoute
  '/_dashboardLayout/settings': typeof DashboardLayoutSettingsRoute
  '/_dashboardLayout/articles/$id': typeof DashboardLayoutArticlesIdRoute
  '/_dashboardLayout/articles/new': typeof DashboardLayoutArticlesNewRoute
  '/_dashboardLayout/courses/new': typeof DashboardLayoutCoursesNewRoute
  '/_dashboardLayout/invite-codes/new': typeof DashboardLayoutInviteCodesNewRoute
  '/_dashboardLayout/users/$id': typeof DashboardLayoutUsersIdRoute
  '/_dashboardLayout/articles/': typeof DashboardLayoutArticlesIndexRoute
  '/_dashboardLayout/courses/': typeof DashboardLayoutCoursesIndexRoute
  '/_dashboardLayout/invite-codes/': typeof DashboardLayoutInviteCodesIndexRoute
  '/_dashboardLayout/resources/': typeof DashboardLayoutResourcesIndexRoute
  '/_dashboardLayout/users/': typeof DashboardLayoutUsersIndexRoute
  '/_dashboardLayout/articles/edit/$id': typeof DashboardLayoutArticlesEditIdRoute
  '/_dashboardLayout/courses/edit/$id': typeof DashboardLayoutCoursesEditIdRoute
  '/_dashboardLayout/invite-codes/edit/$id': typeof DashboardLayoutInviteCodesEditIdRoute
  '/_dashboardLayout/courses/lessons/$lessonId/edit': typeof DashboardLayoutCoursesLessonsLessonIdEditRoute
  '/_dashboardLayout/courses/sections/$sectionId/edit': typeof DashboardLayoutCoursesSectionsSectionIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/github-callback'
    | '/google-callback'
    | '/activity'
    | '/app-settings'
    | '/broadcast'
    | '/channels'
    | '/dashboard'
    | '/settings'
    | '/articles/$id'
    | '/articles/new'
    | '/courses/new'
    | '/invite-codes/new'
    | '/users/$id'
    | '/articles'
    | '/courses'
    | '/invite-codes'
    | '/resources'
    | '/users'
    | '/articles/edit/$id'
    | '/courses/edit/$id'
    | '/invite-codes/edit/$id'
    | '/courses/lessons/$lessonId/edit'
    | '/courses/sections/$sectionId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/github-callback'
    | '/google-callback'
    | '/activity'
    | '/app-settings'
    | '/broadcast'
    | '/channels'
    | '/dashboard'
    | '/settings'
    | '/articles/$id'
    | '/articles/new'
    | '/courses/new'
    | '/invite-codes/new'
    | '/users/$id'
    | '/articles'
    | '/courses'
    | '/invite-codes'
    | '/resources'
    | '/users'
    | '/articles/edit/$id'
    | '/courses/edit/$id'
    | '/invite-codes/edit/$id'
    | '/courses/lessons/$lessonId/edit'
    | '/courses/sections/$sectionId/edit'
  id:
    | '__root__'
    | '/'
    | '/_dashboardLayout'
    | '/github-callback'
    | '/google-callback'
    | '/_dashboardLayout/activity'
    | '/_dashboardLayout/app-settings'
    | '/_dashboardLayout/broadcast'
    | '/_dashboardLayout/channels'
    | '/_dashboardLayout/dashboard'
    | '/_dashboardLayout/settings'
    | '/_dashboardLayout/articles/$id'
    | '/_dashboardLayout/articles/new'
    | '/_dashboardLayout/courses/new'
    | '/_dashboardLayout/invite-codes/new'
    | '/_dashboardLayout/users/$id'
    | '/_dashboardLayout/articles/'
    | '/_dashboardLayout/courses/'
    | '/_dashboardLayout/invite-codes/'
    | '/_dashboardLayout/resources/'
    | '/_dashboardLayout/users/'
    | '/_dashboardLayout/articles/edit/$id'
    | '/_dashboardLayout/courses/edit/$id'
    | '/_dashboardLayout/invite-codes/edit/$id'
    | '/_dashboardLayout/courses/lessons/$lessonId/edit'
    | '/_dashboardLayout/courses/sections/$sectionId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  GithubCallbackRoute: typeof GithubCallbackRoute
  GoogleCallbackRoute: typeof GoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/google-callback': {
      id: '/google-callback'
      path: '/google-callback'
      fullPath: '/google-callback'
      preLoaderRoute: typeof GoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github-callback': {
      id: '/github-callback'
      path: '/github-callback'
      fullPath: '/github-callback'
      preLoaderRoute: typeof GithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboardLayout': {
      id: '/_dashboardLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboardLayout/settings': {
      id: '/_dashboardLayout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardLayoutSettingsRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/dashboard': {
      id: '/_dashboardLayout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutDashboardRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/channels': {
      id: '/_dashboardLayout/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof DashboardLayoutChannelsRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/broadcast': {
      id: '/_dashboardLayout/broadcast'
      path: '/broadcast'
      fullPath: '/broadcast'
      preLoaderRoute: typeof DashboardLayoutBroadcastRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/app-settings': {
      id: '/_dashboardLayout/app-settings'
      path: '/app-settings'
      fullPath: '/app-settings'
      preLoaderRoute: typeof DashboardLayoutAppSettingsRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/activity': {
      id: '/_dashboardLayout/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof DashboardLayoutActivityRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/users/': {
      id: '/_dashboardLayout/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof DashboardLayoutUsersIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/resources/': {
      id: '/_dashboardLayout/resources/'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof DashboardLayoutResourcesIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/invite-codes/': {
      id: '/_dashboardLayout/invite-codes/'
      path: '/invite-codes'
      fullPath: '/invite-codes'
      preLoaderRoute: typeof DashboardLayoutInviteCodesIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/courses/': {
      id: '/_dashboardLayout/courses/'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof DashboardLayoutCoursesIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/articles/': {
      id: '/_dashboardLayout/articles/'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof DashboardLayoutArticlesIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/users/$id': {
      id: '/_dashboardLayout/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof DashboardLayoutUsersIdRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/invite-codes/new': {
      id: '/_dashboardLayout/invite-codes/new'
      path: '/invite-codes/new'
      fullPath: '/invite-codes/new'
      preLoaderRoute: typeof DashboardLayoutInviteCodesNewRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/courses/new': {
      id: '/_dashboardLayout/courses/new'
      path: '/courses/new'
      fullPath: '/courses/new'
      preLoaderRoute: typeof DashboardLayoutCoursesNewRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/articles/new': {
      id: '/_dashboardLayout/articles/new'
      path: '/articles/new'
      fullPath: '/articles/new'
      preLoaderRoute: typeof DashboardLayoutArticlesNewRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/articles/$id': {
      id: '/_dashboardLayout/articles/$id'
      path: '/articles/$id'
      fullPath: '/articles/$id'
      preLoaderRoute: typeof DashboardLayoutArticlesIdRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/invite-codes/edit/$id': {
      id: '/_dashboardLayout/invite-codes/edit/$id'
      path: '/invite-codes/edit/$id'
      fullPath: '/invite-codes/edit/$id'
      preLoaderRoute: typeof DashboardLayoutInviteCodesEditIdRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/courses/edit/$id': {
      id: '/_dashboardLayout/courses/edit/$id'
      path: '/courses/edit/$id'
      fullPath: '/courses/edit/$id'
      preLoaderRoute: typeof DashboardLayoutCoursesEditIdRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/articles/edit/$id': {
      id: '/_dashboardLayout/articles/edit/$id'
      path: '/articles/edit/$id'
      fullPath: '/articles/edit/$id'
      preLoaderRoute: typeof DashboardLayoutArticlesEditIdRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/courses/sections/$sectionId/edit': {
      id: '/_dashboardLayout/courses/sections/$sectionId/edit'
      path: '/courses/sections/$sectionId/edit'
      fullPath: '/courses/sections/$sectionId/edit'
      preLoaderRoute: typeof DashboardLayoutCoursesSectionsSectionIdEditRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/courses/lessons/$lessonId/edit': {
      id: '/_dashboardLayout/courses/lessons/$lessonId/edit'
      path: '/courses/lessons/$lessonId/edit'
      fullPath: '/courses/lessons/$lessonId/edit'
      preLoaderRoute: typeof DashboardLayoutCoursesLessonsLessonIdEditRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
  }
}

interface DashboardLayoutRouteChildren {
  DashboardLayoutActivityRoute: typeof DashboardLayoutActivityRoute
  DashboardLayoutAppSettingsRoute: typeof DashboardLayoutAppSettingsRoute
  DashboardLayoutBroadcastRoute: typeof DashboardLayoutBroadcastRoute
  DashboardLayoutChannelsRoute: typeof DashboardLayoutChannelsRoute
  DashboardLayoutDashboardRoute: typeof DashboardLayoutDashboardRoute
  DashboardLayoutSettingsRoute: typeof DashboardLayoutSettingsRoute
  DashboardLayoutArticlesIdRoute: typeof DashboardLayoutArticlesIdRoute
  DashboardLayoutArticlesNewRoute: typeof DashboardLayoutArticlesNewRoute
  DashboardLayoutCoursesNewRoute: typeof DashboardLayoutCoursesNewRoute
  DashboardLayoutInviteCodesNewRoute: typeof DashboardLayoutInviteCodesNewRoute
  DashboardLayoutUsersIdRoute: typeof DashboardLayoutUsersIdRoute
  DashboardLayoutArticlesIndexRoute: typeof DashboardLayoutArticlesIndexRoute
  DashboardLayoutCoursesIndexRoute: typeof DashboardLayoutCoursesIndexRoute
  DashboardLayoutInviteCodesIndexRoute: typeof DashboardLayoutInviteCodesIndexRoute
  DashboardLayoutResourcesIndexRoute: typeof DashboardLayoutResourcesIndexRoute
  DashboardLayoutUsersIndexRoute: typeof DashboardLayoutUsersIndexRoute
  DashboardLayoutArticlesEditIdRoute: typeof DashboardLayoutArticlesEditIdRoute
  DashboardLayoutCoursesEditIdRoute: typeof DashboardLayoutCoursesEditIdRoute
  DashboardLayoutInviteCodesEditIdRoute: typeof DashboardLayoutInviteCodesEditIdRoute
  DashboardLayoutCoursesLessonsLessonIdEditRoute: typeof DashboardLayoutCoursesLessonsLessonIdEditRoute
  DashboardLayoutCoursesSectionsSectionIdEditRoute: typeof DashboardLayoutCoursesSectionsSectionIdEditRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardLayoutActivityRoute: DashboardLayoutActivityRoute,
  DashboardLayoutAppSettingsRoute: DashboardLayoutAppSettingsRoute,
  DashboardLayoutBroadcastRoute: DashboardLayoutBroadcastRoute,
  DashboardLayoutChannelsRoute: DashboardLayoutChannelsRoute,
  DashboardLayoutDashboardRoute: DashboardLayoutDashboardRoute,
  DashboardLayoutSettingsRoute: DashboardLayoutSettingsRoute,
  DashboardLayoutArticlesIdRoute: DashboardLayoutArticlesIdRoute,
  DashboardLayoutArticlesNewRoute: DashboardLayoutArticlesNewRoute,
  DashboardLayoutCoursesNewRoute: DashboardLayoutCoursesNewRoute,
  DashboardLayoutInviteCodesNewRoute: DashboardLayoutInviteCodesNewRoute,
  DashboardLayoutUsersIdRoute: DashboardLayoutUsersIdRoute,
  DashboardLayoutArticlesIndexRoute: DashboardLayoutArticlesIndexRoute,
  DashboardLayoutCoursesIndexRoute: DashboardLayoutCoursesIndexRoute,
  DashboardLayoutInviteCodesIndexRoute: DashboardLayoutInviteCodesIndexRoute,
  DashboardLayoutResourcesIndexRoute: DashboardLayoutResourcesIndexRoute,
  DashboardLayoutUsersIndexRoute: DashboardLayoutUsersIndexRoute,
  DashboardLayoutArticlesEditIdRoute: DashboardLayoutArticlesEditIdRoute,
  DashboardLayoutCoursesEditIdRoute: DashboardLayoutCoursesEditIdRoute,
  DashboardLayoutInviteCodesEditIdRoute: DashboardLayoutInviteCodesEditIdRoute,
  DashboardLayoutCoursesLessonsLessonIdEditRoute:
    DashboardLayoutCoursesLessonsLessonIdEditRoute,
  DashboardLayoutCoursesSectionsSectionIdEditRoute:
    DashboardLayoutCoursesSectionsSectionIdEditRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  GithubCallbackRoute: GithubCallbackRoute,
  GoogleCallbackRoute: GoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
