"""Adding is_pinned status

Revision ID: 1a2ec6143542
Revises: 29b8bc6cd142
Create Date: 2025-11-03 01:12:00.856797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '1a2ec6143542'
down_revision: Union[str, Sequence[str], None] = '29b8bc6cd142'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('is_pinned', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'is_pinned')
    # ### end Alembic commands ###
