"""adding appsettings model

Revision ID: 29b8bc6cd142
Revises: eb7f57b7c9ab
Create Date: 2025-10-26 21:04:45.584547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '29b8bc6cd142'
down_revision: Union[str, Sequence[str], None] = 'eb7f57b7c9ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('app_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('app_logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('enable_sign_up', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_settings')
    # ### end Alembic commands ###
