"""Add password_reset table

Revision ID: 849e3d83ebe3
Revises: 516d180bb1a9
Create Date: 2025-11-12 20:32:43.019449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '849e3d83ebe3'
down_revision: Union[str, Sequence[str], None] = '516d180bb1a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'USED', 'EXPIRED', name='passwordresetstatus'), nullable=False),
    sa.Column('expires_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_code'), 'password_reset', ['code'], unique=True)
    op.create_index(op.f('ix_password_reset_email'), 'password_reset', ['email'], unique=False)
    op.drop_table('poll_vote')
    op.drop_table('poll_option')
    op.drop_table('poll')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poll_option',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('poll_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vote_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], name='poll_option_poll_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='poll_option_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('poll',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('duration_hours', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('total_votes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='poll_post_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='poll_pkey'),
    sa.UniqueConstraint('post_id', name='poll_post_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('poll_vote',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('poll_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('option_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['poll_option.id'], name=op.f('poll_vote_option_id_fkey')),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], name=op.f('poll_vote_poll_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('poll_vote_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('poll_vote_pkey'))
    )
    op.drop_index(op.f('ix_password_reset_email'), table_name='password_reset')
    op.drop_index(op.f('ix_password_reset_code'), table_name='password_reset')
    op.drop_table('password_reset')
    # ### end Alembic commands ###
