"""adding poll to posttype enum

Revision ID: af3b29df0a5e
Revises: 53f3e669b89e
Create Date: 2025-11-07 11:56:46.034482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'af3b29df0a5e'
down_revision: Union[str, Sequence[str], None] = '53f3e669b89e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Update PostType enum to include POLL
    op.execute("ALTER TYPE posttype ADD VALUE 'POLL' BEFORE 'POST'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # PostgreSQL doesn't support removing enum values, so we can't downgrade
    # This is a limitation of PostgreSQL enums
    pass
    # ### end Alembic commands ###
